builders:
  controllable_generator:
    import: "package:controllable_generator/builder.dart"
    builder_factories: ["controllableGenerator"]
    build_extensions: { ".dart": [".g.dart"] }
    auto_apply: dependents
    build_to: source
    # applies_builders: ["source_gen|combining_builder"]