builders:
  controllable_generator:
    import: "package:controllable_generator/builder.dart"
    builder_factories: ["controllableGenerator"]
    build_extensions: { ".dart": [".x.dart"] }
    auto_apply: dependents
    build_to: source